packaging_format = 2

id = "guacamole"
name = "Guacamole"
description.en = "Clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH"
description.fr = "Service de bureau à distance sans client. Fonctionne avec des protocoles standard comme VNC, RDP, et SSH"

version = "1.5.1~ynh1"

maintainers = ["Jules Bertholet"]

[upstream]
license = "Apache-2.0"
website = "https://guacamole.apache.org/"
admindoc = "https://guacamole.apache.org/doc/gug/"
code = "https://github.com/search?utf8=%E2%9C%93&q=repo%3Aapache%2Fguacamole-server+repo%3Aapache%2Fguacamole-client+repo%3Aapache%2Fguacamole-website&type=Repositories&ref=searchresults"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/guacamole"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    help.en = "Not recommended"
    help.fr = "Pas reccomandé"
    type = "group"
    default = false

[resources]
    [resources.sources]
        [resources.sources.auth-header]
        url = "https://downloads.apache.org/guacamole/1.5.2/binary/guacamole-auth-header-1.5.2.tar.gz"
        sha256 = "c80c11de87993e1732d65c059d53d400961afcf61e7c12501bc2197002af7730"

        [resources.sources.mariadb-java-client]
        url = "https://downloads.mariadb.com/Connectors/java/connector-java-2.7.4/mariadb-java-client-2.7.4.jar"
        sha256 = "f06577b19e89b33028b96cd4f031248e761de7ebc712f4ef535e268df76edb2a"

        [resources.sources.auth-ldap]
        url = "https://downloads.apache.org/guacamole/1.5.1/binary/guacamole-auth-ldap-1.5.1.tar.gz"
        sha256 = "4d32bb2aab09f9f99d02faa3db82c7c9ff3e5f84de9b042fba3a5f745f2704e8"

        [resources.sources.client]
        url = "https://downloads.apache.org/guacamole/1.5.2/binary/guacamole-1.5.2.war"
        sha256 = "86efc30016e4038948d8c1a5c37a0b05e38dadd3104db6ec03755bc6e3111c40"
        in_subdir = false

        [resources.sources.server]
        url = "https://downloads.apache.org/guacamole/1.5.1/source/guacamole-server-1.5.1.tar.gz"
        sha256 = "aabd707a68b99253f87234d0c3884678d6d6c1bceb39e7f9943c69d5329f4501"

        [resources.sources.tomcat9_deb]
        url = "https://ftp.debian.org/debian/pool/main/t/tomcat9/tomcat9_9.0.70-1_all.deb"
        sha256 = "c062cd3ff27a566fdc6fed7dd2602c4e4ffe2216c8a19822bcaf03bd739e39b5"
        format = "ar"
        rename = "tomcat9.deb"

        [resources.sources.auth-jdbc]
        url = "https://downloads.apache.org/guacamole/1.5.1/binary/guacamole-auth-jdbc-1.5.1.tar.gz"
        sha256 = "daf293856ddc2664b862a53b3f232ece82925832c081238161f27c49081b4305"

    [resources.ports]
    main.default = 8080
    guacd.default = 4822

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server acl build-essential libcairo2 libjpeg62-turbo-dev libpng-dev libtool-bin libossp-uuid-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev freerdp2-dev libpango1.0-dev libssh2-1-dev libtelnet-dev libvncserver-dev libwebsockets-dev libpulse-dev libssl-dev libvorbis-dev libwebp-dev tomcat9"

    [resources.database]
    type = "mysql"
